[env:pda2]
platform = espressif32
board = pda2
framework = arduino

board_build.flash_size = 16MB
board_build.partitions = partitions.csv

monitor_speed = 115200
upload_port = COM8

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    lvgl/lvgl @ 9.2.1

build_flags =
    -I include
    -I lib/PDA2Core/src
    -DLV_CONF_INCLUDE_SIMPLE

; ⚠️ НИКОГДА не добавлять:
;   -DARDUINO_USB_MODE=1
;   -DARDUINO_USB_CDC_ON_BOOT=1
; -DBOARD_HAS_PSRAM и -DPDA2_BOARD — уже в boards/pda2.json